name: kafka-server integration

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: ec2 SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.KAFKA_SERVER_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo ${KAFKA_SERVER_HOST}
            cd /home/ubuntu/msa-kafka-server
            git pull origin master
            docker compose pull
            docker compose up -d
            